// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  enum: {
    ASC: 'ASC';
    DESC: 'DESC';
    ACTIVE: 'ACTIVE';
    INACTIVE: 'INACTIVE';
  };
  root: {
    'theme-mode': 'Dark Mode';
    'language-switch': 'Language';
  };
  error: {
    title: 'An unexpected error occurred while loading the page.';
    content: 'Please try again shortly, or go back to the previous page.';
    button: 'Go Back';
  };
  'not-found': {
    title: '404 PAGE NOT FOUND';
    content: "This page doesn't exist.";
    button: 'Go to Home';
  };
  hmgma: {
    search: 'Search';
    sort: 'Sort';
    filter: 'Filter';
    date: 'Date';
    license: 'License';
    reset: 'Reset';
  };
  todo: {
    title: 'To Do List';
    'sub-title-1': 'Before Luncher';
    'sub-title-2': 'After Luncher';
  };
};
export default messages;
